<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class LN_Jalan_Samarinda extends Model
{
    use HasFactory;

    protected $table = 't_ln_jalan_samarinda';

    protected $fillable = [
        'NAME',
        'LAYER',
        'OBJECTID_1',
        'OBJECTID',
        'Kl_Dat_Das',
        'Nm_Ruas',
        'Thn_Data',
        'Status',
        'Fungsi',
        'Mendukung',
        'Ura_Dukung',
        'Kd_Bd_PU',
        'Kd_Jns_Inf',
        'Kd_Inf',
        'Propinsi',
        'Kab_Kot',
        'Kecamatan',
        'Desa_Kel',
        'Tk_Ruas_Aw',
        'Tk_Ruas_Ak',
        'Kd_Patok',
        'Km_Awal',
        'Km_Akhir',
        'Nm_Lintas',
        'Kon_Baik',
        'Kon_Sdg',
        'Kon_Rgn',
        'Kon_Rusak',
        'Kon_Mntp',
        'Kon_T_Mntp',
        'Panjang',
        'Lbr_Keras',
        'LHRT',
        'VCR',
        'Tipe_Jln',
        'MST',
        'Tanah_Kri',
        'Macadam',
        'Aspal',
        'Rigid',
        'Thn_Pen_Ak',
        'Jns_Pen',
        'Koord_X_Aw',
        'Koord_Y_Aw',
        'Koord_X_Ak',
        'Koord_Y_Ak',
        'Shape_Leng',
        'Shape_Le_1',
        'LENGTH',
        'LENGTH_3D',
        'BEARING',
        'LINE_STYLE',
        'LINE_COLOR',
        'LINE_WIDTH',
        'FONT_SIZE',
        'FONT_COLOR',
        'FONT_CHARS',
        'FONT_WEIGH',
        'ELEVATION',
        'MAP_NAME',
        'GM_LAYER',
        'GM_TYPE',
        'version',
        'highway',
        'osm_id',
        'oneway',
        'boat',
        'smoothness',
        'START_TIME',
        'END_TIME',
        'Kord_X_Awa',
        'Kord_X_Akh',
        'Kord_Y_Awa',
        'Kord_Y_Akh',
        'Kord_Y_a_1',
        'geom'
    ];

    protected $casts = [
        'geom' => 'string',
        'OBJECTID_1' => 'integer',
        'OBJECTID' => 'integer',
        'Thn_Data' => 'integer',
        'Km_Awal' => 'integer',
        'Km_Akhir' => 'integer',
        'Kon_Baik' => 'decimal:3',
        'Kon_Sdg' => 'decimal:3',
        'Kon_Rgn' => 'decimal:3',
        'Kon_Rusak' => 'decimal:3',
        'Kon_Mntp' => 'decimal:3',
        'Kon_T_Mntp' => 'decimal:3',
        'Panjang' => 'decimal:3',
        'Lbr_Keras' => 'decimal:1',
        'LHRT' => 'decimal:1',
        'VCR' => 'decimal:1',
        'Tipe_Jln' => 'decimal:1',
        'MST' => 'decimal:1',
        'Tanah_Kri' => 'decimal:1',
        'Macadam' => 'decimal:1',
        'Aspal' => 'decimal:1',
        'Rigid' => 'decimal:1',
        'Thn_Pen_Ak' => 'integer',
        'Koord_X_Aw' => 'decimal:9',
        'Koord_Y_Aw' => 'decimal:9',
        'Koord_X_Ak' => 'decimal:9',
        'Koord_Y_Ak' => 'decimal:9',
        'Shape_Leng' => 'decimal:10',
        'Shape_Le_1' => 'decimal:10',
        'version' => 'integer',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
    ];
}