<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PtHasilLokasiSurveiEsdm extends Model
{
    use HasFactory;

    protected $table = 't_pt_hasil_lokasi_survei_esdm';

    protected $fillable = [
        'Lokasi',
        'NAMOBJ',
        'LUASWH',
        'TIPADM',
        'WADMKC',
        'WADMKD',
        'WADMKK',
        'WADMPR',
        'Status',
        'Kode_Kota',
        'Kode_L',
        'Lokasi_Ke',
        'Kodifikasi',
        'DUSUN',
        'JUMLAH_RT',
        'KET_RT',
        'J_Pnddk',
        'J_KK',
        'J_BRumah',
        'J_BFasum',
        'Ket_BFasum',
        'S_L_Kom',
        'N_S_L',
        'K_S_L',
        'S_P_L',
        'W_NYALA',
        'L_NYALA',
        'T_SL',
        'Knd_S_L',
        'Koor_X',
        'Koor_Y',
        'PR_Prov',
        'K_Hutan',
        'Izin_Lain',
        'Potensi',
        'R_JUTAMA',
        'R_JLISTRIK',
        'K_Jalan',
        'L_Jalan',
        'P_Jalan',
        'PENYULANG',
        'R_S_L',
        'KENDALA',
        'I_IUPT',
        'I_PPBH',
        'I_IUPK',
        'J_Gardu',
        'B_Gardu',
        'S_L_P',
        'K_RPLTS',
        'Panjang',
        'Tiang',
        'Biaya',
        'Skor_A',
        'Skor_J',
        'K_PR',
        'K_Izin',
        'K_Hutan_1',
        'S_Arah',
        'S_Potensi',
        'S_J_P',
        'T_S',
        'Cek',
        'Priorita_1',
        'B_PLTS',
        'geom'
    ];

    protected $casts = [
        'LUASWH' => 'decimal:2',
        'TIPADM' => 'integer',
        'Lokasi_Ke' => 'integer',
        'JUMLAH_RT' => 'integer',
        'J_Pnddk' => 'integer',
        'J_KK' => 'integer',
        'J_BRumah' => 'integer',
        'J_BFasum' => 'integer',
        'L_NYALA' => 'decimal:2',
        'T_SL' => 'decimal:2',
        'R_JUTAMA' => 'decimal:2',
        'R_JLISTRIK' => 'decimal:2',
        'L_Jalan' => 'decimal:2',
        'Panjang' => 'decimal:2',
        'Tiang' => 'decimal:2',
        'Biaya' => 'decimal:2',
        'Skor_A' => 'integer',
        'Skor_J' => 'integer',
        'S_Arah' => 'integer',
        'S_Potensi' => 'integer',
        'S_J_P' => 'integer',
        'T_S' => 'integer',
        'geom' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
    ];
}